### ISSUE TITLE
Failed uploads fail to save as succeeded

### ISSUE THREAD

**Issue by eivindveg** [eivindveg/HotSUploader#107]
HotSLogs recently had some maintenance resulting in a bunch of failed uploads. When the service came back up, the replays were uploaded successfully, but their local status is unchanged upon application restart. As they're removed from the list on retry, this indicates an issue with their persistence to the database.

**Comment by zhedar** [comment]
So what could we do about that? We can't always check the whole DB for non-present uploads.
We would need some feedback from hotslogs with the timeframe of such an action, which probably isn't that easy and straightforward to implement for @barrett777 .

**Comment by barrett777** [comment]
I think there's some confusion here.  HOTS Logs shouldn't ever give a false 'Success' message

If HOTS Logs is down (planned or unplanned), all replay uploads will return 'Maintenance.'

If you get a 'Maintenance' message, I think the best action would be to tell the user and close the program.

**Comment by zhedar** [comment]
I think what happened here was that you removed some games (for example with LI Ming at her release) and these games were not reuploaded after the removal, since they were already marked as uploaded.

**Comment by barrett777** [comment]
Ooh yeah.  If I ever have to delete messages, I put a note on the home page, and usually give a time frame guiding users on what replays to reupload.

**Comment by eivindveg** [comment]
Will push a test verifying this behaviour on the Spring branch. I've also gotten a mislocation of a Windows folder that @barrett777's app couldn't handle as well. Once these two are solved and backed with tests, we might need to release 2.0.3, albeit without the tests, as they're part of the 2.1 branch.

**Comment by eivindveg** [comment]
Got a working test for this with no major effort on the hotfix branch. However, the test behaviour is really wonky - there's really no wonder this is broken.
