### ISSUE TITLE
Uploader not detecting replay folder

### ISSUE THREAD

**Issue by JMTibbles** [eivindveg/HotSUploader#108]
Uploader status is Idle.

My replay folder is located in D:\Users\J.Michael\Documents\Heroes of the Storm\Accounts\682598\1-Hero-1-6896\Replays\Multiplayer

**Comment by eivindveg** [comment]
Hi,

Thanks for dropping this here. Based on what you told me, can you confirm that you moved your documents folder through the "Documents Properties" Windows prompt?

What is the output from running the following command in cmd.exe?
```reg query "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders" /v personal```

The application is installed in {{USERDIR}}\AppData\Local\HotS Replay Uploader. Could you run the exe there in cmd and paste the output to http://pastebin.com/?

**Comment by eivindveg** [comment]
Having tested the required RexExp for validating the registry query, it does not support dots in folders. This will be fixed for 2.0.3 which should be released this weekend.

**Comment by JMTibbles** [comment]
Correct.  My documents folder was moved through "Documents Properties."

The command returned HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders
    personal    REG_SZ    D:\Users\J.Michael\Documents

When I run the .exe in cmd it just launches the program and doesn't output anything.  I think I'm doing it wrong.

**Comment by eivindveg** [comment]
fixed in f3fd29f

**Comment by eivindveg** [comment]
Version 2.0.3, which includes this fix, has now been released.
