### ISSUE TITLE
[Windows 10] Uploader does not detect replays

### ISSUE THREAD

**Issue by saapa** [eivindveg/HotSUploader#110]
After I deleted all replays in the default folder, HoTS Replay Uploader will not upload any further replays saved there by the game. Replays are saved in C:\Users\[username]\Documents\Heroes of the Storm\Accounts\100331011\2-Hero-1-642104\Replays\Multiplayer
My Windows username does not include a dot(.)
I've uninstalled the game once in order to install it on my SSD drive. Replay folder has not moved.

**Comment by minlexx** [comment]
@saapa maybe your username contains other interesting characters? :D

**Comment by saapa** [comment]
Only letters. No ü or ã or è or the likes.

**Comment by eivindveg** [comment]
I will, unfortunately, require your username in order to properly sample the regular expression used.

**Comment by saapa** [comment]
Fine, the full path is C:\Users\saapa\Documents\Heroes of the Storm\Accounts\100331011\2-Hero-1-642104\Replays\Multiplayer

**Comment by eivindveg** [comment]
That path matches. The only likely scenario is that the cleanup is not happening properly. Deleting USERHOME\Documents\HotSReplayUploader\ or the .db files in that folder should fix the issue.

**Comment by saapa** [comment]
Deleting the two .db files in the folder have fixed the issue. It found all the replays and started uploading them.
