### ISSUE TITLE
hero.gg as well?

### ISSUE THREAD

**Issue by johnafogarty4** [eivindveg/HotSUploader#111]
Less of a issue, more of a feature request, could you also include a way to upload to both HotsLOGS and Hero.GG?

**Comment by zhedar** [comment]
Multi provider support was once discussed, but then dropped due to a poll result posted on reddit. Unless many 
users changed services, there won't be a high chance this will be implemented.

**Comment by eivindveg** [comment]
To expand on @zhedar's comments, the 2.0 release laid down a lot of the remaining ground work for pivoting to another provider, or supporting multi-provider. However, as he said, there's very little interest for multiple providers, both in terms of what people use and what they'd like to use.

Furthermore, my limited attempts at contacting Hero.gg for official information haven't resulted in any responses, and the activity of the site itself seems lackluster at best. If this changes, we'll be ready for it, but I strongly believe the HotS community needs to grow first.

**Comment by johnafogarty4** [comment]
Thanks for the information and consideration.

**Comment by eivindveg** [comment]
Just to be clear, it's probably good for the application to have to revisit this every now and then, so we do appreciate the request.
