### ISSUE TITLE
[Feature Request] Possibility to remove alts?

### ISSUE THREAD

**Issue by Sk1nk** [eivindveg/HotSUploader#118]
From time to time I played an alt way back with a friend to support his leveling without him getting enemys on my MMR. But since then the Players Dropdown Menu lists empty slots before I can select my main profile. Could you add a possibility to remove names from the dropdown menu or at least let me select which profile should be shown on startup? Thanks

**Comment by zhedar** [comment]
This would be something we would need a settings system for, but it sounds like something, that is sensible to implement.
Another possibility would be to show the player with the most / recents games as default.

**Comment by Sk1nk** [comment]
Either of those would do the job for me :)

**Comment by rogusdev** [comment]
I implemented the sort approach to resolve this issue.  Unless someone had lots and lots of accounts on one machine, I think this is a reasonable low effort approach.
