### ISSUE TITLE
Brawl Replays do not upload, do not clear

### ISSUE THREAD

**Issue by mgius** [eivindveg/HotSUploader#138]
I have a growing list of games that won't upload in my application.  This morning I saw Lost Cavern matches and realized they're Heroes Brawl matches.

When I click the re-try button it fails to upload again, when I click the Trash button they come back the next time I launch the uploader.

There needs to be some way to get these replays out of the list without having to delete the underlying replays.

**Comment by mgius** [comment]
There's a probably whole pile of things that can or should be done here, but I feel like at the least replays which are Trash binned should be marked as uploaded so they don't reappear.  

At best the uploader should detect Brawl matches and decline to upload them as long as HotsLogs doesn't accept them.  This is super dependent upon what the underlying replay library can handle, so it may not be feasible to do without first patching the replay library.

**Comment by eivindveg** [comment]
I've been meaning to check the game type. @barrett777's parser received a pull request lately, so it should be easily doable: https://github.com/barrett777/Heroes.ReplayParser/commit/c514e937a5148c5aa2b694b379ce354eb9623330

**Comment by eivindveg** [comment]
I've fixed the attempting to upload brawls. The deletion of replays seeming broken probably needs its own issue.

**Comment by eivindveg** [comment]
Fix for brawl uploads will be released as part of 2.1.2, which is currently in note drafting.

**Comment by mgius** [comment]
First time it ran the replays were still in the failed list.  Clicked trash and re-started uploader and they stayed gone.  Looks like you got it.

**Comment by eivindveg** [comment]
Retracing those steps, I think the following happened:
* The replays had their state preserved as failed - retrying at this point would have properly tagged them as unsupported.
* You deleted the tracking state of the files, but the file deletion somehow failed - this needs checking and handling
* The application loaded and discovered the replays as new.
* The application "uploaded" the replays as if they were new, tagging them as unsupported.

I'll make sure to review the deletion step.

**Comment by HiPhiSch** [comment]
Brawls are now supported ^^

**Comment by barrett777** [comment]
:)

**Comment by eivindveg** [comment]
Will revert for 2.1.3 or 2.2.0, whichever has a high priority.

**Comment by mgius** [comment]
![Well I feel sheepish](https://adventuresofthemeems.files.wordpress.com/2013/10/i-feel-sheepish.jpg)

**Comment by eivindveg** [comment]
Heh. I email @barrett777. I couldashouldaoughta asked him if he planned to support it.

**Comment by barrett777** [comment]
Well it would be good for you to prepare for future weirdness from Hots
Logs anyway.

Each of Blizzard's weekly brawl replays are unique and unusual; I'm sure
there will be more in the future that also fail with the 'UnexpectedResult'
upload status, at least until I can respond to it

On Thu, Nov 10, 2016 at 1:07 PM, Eivind Vegsundvåg <notifications@github.com

**Comment by eivindveg** [comment]
That handling sounds like a job for #117, with an error message such as "We identified this replay as a Brawl, but HotsLogs could not handle it. Please retry it at a later date."

**Comment by eivindveg** [comment]
Weirdness from da9a87f being merged into develop - this is resolved again in a5868af8

**Comment by eivindveg** [comment]
Release is being prepared. However, @zhedar is not available right now, so we're waiting with publishing the release until he has time to press his buttons.
