### ISSUE TITLE
Update padding in lookup textboxes to match player profile dropdown

### ISSUE THREAD

**Issue by lorddev** [eivindveg/HotSUploader#144]
![screenclip](https://cloud.githubusercontent.com/assets/2220085/20457989/3b32063a-ae4d-11e6-9f05-54dfc861e364.png)

**Comment by lorddev** [comment]
@eivindveg I updated the css locally but I'm unable to build. The resulting jar files throw an exception after showing the HotS Uploader loading animation.

**Comment by eivindveg** [comment]
Does it build without your changes?

**Comment by eivindveg** [comment]
The resulting jar will be more stable if you pull develop now.

**Comment by lorddev** [comment]
This is what I see now:
```
PS C:\projects\HotSUploader\target> java -jar project.artifactId.jar
no main manifest attribute, in project.artifactId.jar
```

**Comment by eivindveg** [comment]
This command works for me:
```
D:\Workspaces\HotSUploader\target>java -jar "HotS Replay Uploader-boot.jar"
```
Make sure your branch is based from the newest develop.

**Comment by lorddev** [comment]
I am on the latest develop. That file doesn't exist, which means it didn't build. If I try to build with Ubuntu Bash, I see
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project hots-replay-uploader: Fatal error compiling: invalid target release: 1.8 -> [Help 1]
```
If I run `java -version` from Ubuntu bash it says 1.7.0_121 even though I have JDK 8 installed.

**Comment by eivindveg** [comment]
Aha. Please try:
```
echo %JAVA_HOME%
```

**Comment by lorddev** [comment]
```
root@SNAPLORD:/mnt/c/projects/HotSUploader# echo %JAVA_HOME%
%JAVA_HOME%
```

**Comment by eivindveg** [comment]
That's your Linux Subsystem, which I'm unsure how acts for Windows. The appropriate command in this case would be:
```
echo $JAVA_HOME
```
Please run the original command I specified under your Windows shell, not the Linux Subsystem.

**Comment by lorddev** [comment]
If I build from cmd.exe instead of Powershell, it builds properly. However, there is still no "HotS Replay Uploader-boot.jar" file it the target folder.

**Comment by eivindveg** [comment]
Try pulling my develop in to your branch. The 2.1 branch was broken for jars until 2.1.3, and I forgot to merge the hotfix branch into develop until just now.

**Comment by lorddev** [comment]
![image](https://cloud.githubusercontent.com/assets/2220085/20678355/3b621294-b54b-11e6-9b82-b9a7c0cfce72.png)

**Comment by eivindveg** [comment]
Oh yes. This is an issue indeed.

**Comment by eivindveg** [comment]
This is embarassing. Fixed in 08fa6a89

**Comment by lorddev** [comment]
Better! But now I get this: "no main manifest attribute, in HotS Replay Uploader.jar"

**Comment by eivindveg** [comment]
Use the -boot file. The non-boot file is intended for later stages in the build.

**Comment by lorddev** [comment]
Bingo!

**Comment by eivindveg** [comment]
Thank you very much! This change will be part of the 2.2.0 release, and will be credited to you in the change notes. In the event that we release another hotfix for the 2.1 branch of releases, it might be cherrypicked to that too. Feel free to add any relevant information you may want public in the contributors section of pom.xml and submitting a pull request.
