### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by matt-stuart** [eivindveg/HotSUploader#157]
Since 2.0 launched my client has been showing a "Connection Error" message in the top right. Is there a log I can look for for more details?

![screen shot 2017-04-26 at 8 55 57 pm](https://cloud.githubusercontent.com/assets/106377/25466051/530fac74-2ac3-11e7-8848-d9bca7aa1d20.png)

**Comment by kvting** [comment]
Same here

**Comment by eivindveg** [comment]
Will review this after work today.

**Comment by matt-stuart** [comment]
If it means anything, the URL in the source to hit for uploads https://www.hotslogs.com/UploadFile?Source= is responding with not found.

**Comment by eivindveg** [comment]
That's normal - that URL requires some information about the stashed replay file.

**Comment by ulrichsg** [comment]
Same here. It uploaded a whole bunch of pre-2.0 replays without problems, so it's specifically an issue with 2.0 replays.

**Comment by gregahsue** [comment]
I'm seeing this error as well ever since the 2.0 patch.

**Comment by eivindveg** [comment]
If you wish to help me debug this issue a lot faster, please upload one or two problematic replays to Google Drive or Dropbox and link them here. That way I won't have to play entire matches to produce enough data to verify the bug and fixes.

**Comment by ulrichsg** [comment]
Here's one: https://www.dropbox.com/s/xbujcnocu3ciojm/Braxis%20Holdout%20%2839%29.StormReplay?dl=0

**Comment by matt-stuart** [comment]
If you need 3 more: https://www.dropbox.com/sh/i0hheeaeunj14c6/AAC5QjC_7V7SAt-5j77E-GLCa?dl=0

**Comment by eivindveg** [comment]
Thanks alot. Getting right to work!

**Comment by eivindveg** [comment]
Verified fixed in https://github.com/eivindveg/HotSReplayParser/commit/1976764f208abcb830f02763ef36c495f39c88ed

Adding a few finishing touches to the parser, then aiming for a release tonight!

**Comment by eivindveg** [comment]
This issue is resolved in version 2.1.5 which has now been released. Thanks for the extra sample data, it all helped!

**Comment by ulrichsg** [comment]
Works like a charm. Thanks!

**Comment by gregahsue** [comment]
Wow, you fixed it faster than I could upload sample errors. 

Thank you and great job!
