### ISSUE TITLE
Unfinished Match Does not go away

### ISSUE THREAD

**Issue by ehatle** [eivindveg/HotSUploader#161]
<img width="843" alt="screen shot 2017-06-29 at 08 57 05" src="https://user-images.githubusercontent.com/3341171/27697481-39cf6c5a-5ca9-11e7-9b23-e8165c4bc817.png">
Stuck on this screen after HOTS crashed the other day.
Maybe add a button to "Stop tracking this match"?

**Comment by zhedar** [comment]
Yeah, this is actually one thing we have overlooked, but there didn't seem to be the time to fix this. I guess we may need so sit down now and implement a solution like suggested in #159.

A quick workaround for you is to remove the game files, which are left over. You can find those under your temp folder `../Heroes of the Storm/`.

**Comment by catsby** [comment]
~Hi – where exactly is this temp folder?~
Got the answer from #159; for me it was  `/private/var/folders/qh/m63cm1v53vn0vc42k57n7c_40000gn/T/TemporaryItems/Blizzard`

I was worried the stuck file was still in my replays, so I moved replays from `~/Library/Application Support/Blizzard/Heroes of the Storm/Accounts/<digits>/1-Hero-<more digits>/Replays/Multiplayer
` and verified the uploader was un-stuck. I then added in replays I knew to be good. Thanks 👍

**Comment by zhedar** [comment]
I will close this issue in favor of #159. Any progress will be tracked there.
