### ISSUE TITLE
Replays are not uploading

### ISSUE THREAD

**Issue by Eugenii10** [eivindveg/HotSUploader#165]
Hello!
Thanks for a great app! In last time I couldn't upload replays with your app, it just displays exclamation sign. About a month ago it worked like a charm. But I havn't installed any programs which may have ifluence on that. Have your app any debug log, so we could find the reason?
I successfully upload the same replays at site.
Thanks!

**Comment by eivindveg** [comment]
Hi. We currently do not produce any logs. @zhedar has the most experience in producing log output by running the application in a terminal.

**Comment by zhedar** [comment]
Sorry for the inconvenience, we planned to expose log files properly, but didn't get to to it yet. It will probably be included in the next version.
However, you can [download the jar version](https://github.com/eivindveg/HotSUploader/releases/download/v2.1.5/HotS.Replay.Uploader-2.1.5.jar) of the uploader and execute it in a terminal (if you're using Windows, `cmd` will do) via `java -jar path/to..../HotS.Replay.Uploader-2.1.5.jar`. This will yield some log output.
