### ISSUE TITLE
Ubuntu client

### ISSUE THREAD

**Issue by TheCherry** [eivindveg/HotSUploader#17]
Hi, can you make a .jar file for start that application?
I run HOTS under linux with wine.
Or just a short command line way to compile that java thing.

Thanks

**Comment by eivindveg** [comment]
I won't actively support Linux, but can start shipping jar bundles for releases from 1.1. If you have Maven installed, run "mvn clean package" in the command line.

**Comment by TheCherry** [comment]
Thanks, did work after a little edit.
Did fork it, you can pull the commits, if you want.
https://github.com/TheCherry/HotSUploader

**Comment by eivindveg** [comment]
Haven't reviewed the pull request properly yet. How does the Windows version run under Wine? Not at all?

**Comment by TheCherry** [comment]
Did not try wine, but in my mind, should a Java application work for all platforms

**Comment by eivindveg** [comment]
fixed in b96b6e00690203e457e69df76303ebd8e262143d - partial Ubuntu support will be added from 1.1

**Comment by TheCherry** [comment]
Thanks for the merge and the help :smile:

**Comment by eivindveg** [comment]
Nonono. Thank YOU. I had no idea it was this little work. I was expecting to have to reimplement all the OS-specific functionality again, and you did what little there was. Leaves me with no excuse not to merge. ;p

**Comment by eivindveg** [comment]
Reopening issue for the following reason:

I need an official Ubuntu maintainer. Responsibility is to verify the functionality of native artifacts on every release. May include building and publishing of these artifacts if you can do it on short notice.

**Comment by TheCherry** [comment]
Mhh ... why you don't publish just a .jar file for the Linux world? Next someone need a RPM Package or something else and then you have to build even more ...
I can build for you the .deb files, but cant promise that this will be just in time.

**Comment by eivindveg** [comment]
I will upload jars as well. :)

--- Original Message ---

**Comment by TheCherry** [comment]
Well :+1: 
Just a Question ... do you not sleep? You are online, every time xD

**Comment by eivindveg** [comment]
I do sleep. I just happen to be in your timezone. ;p

**Comment by eivindveg** [comment]
Adding you to collaborators so you can upload artifacts.
