### ISSUE TITLE
Native OS X (.app) support

### ISSUE THREAD

**Issue by greatman** [eivindveg/HotSUploader#2]
Instead of spamming /r/hots gonna write here ;)

Add support for native OS X (.app) application support. The solution I used myself for my own project doesn't work with java 8 & FX, it cause a app crash right on start.

Currently trying to automate javaFX bundler with maven-antrun-plugin since Oracle only likes ANT. Gonna write here what I find.

**Comment by eivindveg** [comment]
I assume you're talking about this bundler? 
https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/self-contained-packaging.html

**Comment by greatman** [comment]
Yeah.

**Comment by eivindveg** [comment]
Please also review the following: http://speling.shemnon.com/blog/2014/09/12/maven-javafx-plugin-8-dot-1-released/

**Comment by eivindveg** [comment]
Sorry to rain on your parade; but this issue is halfway fixed. I would love if you could rebase to the branch feature/nativebuilds and make sure the targets build a Mac OSX icon pack and similar. See the link in my previous reply for documentation. Tested on both OSX and Windows, but I only have testing time on OSX, no actual dev time.

**Comment by greatman** [comment]
Ill test it out ;)

**Comment by eivindveg** [comment]
I'll be reassigning this issue to @FredrickB in his capacity as interim Platform Maintainer for OSX until at least the release of Release Candidate 1. He'll be asked to review any experiences and pull requests you share.

**Comment by FredrickB** [comment]
Support implemented, tested on version: OS X 10.9.5 (13F34). DMG and PKG included i milestone 1.0-RC-1

Focused on fixing this issue asap so it got resolved faster than expected.

**Comment by greatman** [comment]
Works on my 10.10.3 install but not my 10.10.3 VM, must just be a VM bug.

**Comment by eivindveg** [comment]
I presume this is due to the JRE bundled being platform dependent and that the native lib implementation is unpredictable on emulated hardware. Could you provide a stack trace to reference in the event that things go wonky on OSX bundles in the future?

**Comment by greatman** [comment]
That's the OS X stack trace:
https://gist.github.com/greatman/e5323f244514366d5671

**Comment by eivindveg** [comment]
Yeah, seems it had issues creating the window renderer on thread 19. I do small bit of blending on logo, I guess this is handled by the graphics renderer. Are you building it on the VM or installing using a bundle from the release?

**Comment by greatman** [comment]
built a copy with mvn clean package. I could try a release one
