### ISSUE TITLE
Application freeze on OS X when closing application

### ISSUE THREAD

**Issue by FredrickB** [eivindveg/HotSUploader#20]
Terminating by either shortcut Cmd+Q or clicking cross icon (windows style) causes the application to freeze. Only option then is to force-quit via activity monitor.

**Comment by eivindveg** [comment]
Is this a regression between 1.1 and 1.1.1, or simply unreported from before?

**Comment by FredrickB** [comment]
Unreported. It was first noticed around tray experimentation on OS X, and was thought to be a sideresult of this. Evidently this is not the case.

**Comment by allanjackson** [comment]
I just upgraded to 1.1.1. The issue was not happening previously, but it is now. I'm pretty sure I was on 1.1 before, so it looks like a regression to me. ps - is there any way to actually tell what version I'm currently running?

**Comment by eivindveg** [comment]
I'm gonna take a stab and guess it's part of the removal on Client line 56 in 14598bff272f291543c59d77b1ba6b508da38610

I removed that to make the tray icon behave properly, so there's probably some loose threads hanging around when we try closing. Could you reimplement that as an else case for the tray icon, and test to see if that solves it? This is pretty major, so we'll have to push out 1.1.2 as soon as it's fixed.

**Comment by chadmbol** [comment]
I have this issue and have not updated to 1.1.1. I am currently using version 1.1. OS 10.10.3 MacBookPro Mid-2012 i5

**Comment by eivindveg** [comment]
Thanks, that makes me confident we're lacking the force exit that disappeared when I implemented the tray notification.

**Comment by FredrickB** [comment]
See pull request https://github.com/eivindveg/HotSUploader/pull/24 for fix.

**Comment by ghosthog** [comment]
I had this error in v 1.1 before 1.1.1 as well.

**Comment by eivindveg** [comment]
This is fixed in 1.1.2, which was released a few hours ago
