### ISSUE TITLE
Change sorting method

### ISSUE THREAD

**Issue by argash** [eivindveg/HotSUploader#21]
Right now the sorting of the list of uploaded files is alphabetical, this should be changed to be by time stamp of the upload. In fact all of the lists should be sorted this way, or by timestamp of the game file itself.

**Comment by eivindveg** [comment]
Agreed. I put in some simple versioning stuff in 1.1 to let me migrate models for changes like this. Will look into this once I get some more time after exams.

**Comment by eivindveg** [comment]
With the new list, the criteria should at the very least change to the following:
New replays before exception replays
Otherwise ordered by last modified time of replay file

**Comment by eivindveg** [comment]
Fixed in fc1b62d152ac7ee3ac4f2d5c6d448f908102d5ff
