### ISSUE TITLE
Problem installing on Windows XP (win32)

### ISSUE THREAD

**Issue by shakedel** [eivindveg/HotSUploader#28]
When installing on Windows XP x86, the installer progress bar finishes and then I get the following error popup:
"Unable to execute file: <path to HotSLogs UploaderFX>\HotSLogs UploaderFX.exe
 CreateProcess failed; code 193.
%1 is illegal in Win32 application.

Note: my windows user name (in the path) contains the '&' sign

**Comment by eivindveg** [comment]
Could you make another user on your computer and try to install using that user? It won't be usable for your primary user, but will narrow down the issue in terms of the ampersand. =)

**Comment by eivindveg** [comment]
Please verify that the .jar download works? It might be an issue with 32bit compatibility, either in the installer or the supplied runtime environment.

**Comment by shakedel** [comment]
tried to use a username with no '&'. Still does not work (same err msg)

**Comment by eivindveg** [comment]
I'm going to assume the issue is I compile in 64bit and the 64bit JRE is supplied. If this becomes an issue with a lot of other Windows users, I'll consider building 32bit artifacts as well. In the meantime, use the jar download with 32bit Java.
