### ISSUE TITLE
Memory leak on OSX

### ISSUE THREAD

**Issue by brentechols34** [eivindveg/HotSUploader#31]
I opened up the uploader today after a couple months of not playing a whole lot, and on launch it has a memory leak that causes it to use all of the system's memory before dying (50GB before osx caught it).
I'm not sure what might cause this, maybe old replay files causing an issue? I'm not sure how to give better repro steps since everything worked the last time I used it. I can give more details if you need!

**Comment by eivindveg** [comment]
Aaand I would thus like to congratulate myself on creating such a vast memory leak not on purpose in Java. Splendid job from me!

Seriously, I'll look around for pointers when working on version 2.0 the coming days.

**Comment by eivindveg** [comment]
Also, could you check network traffic and memory usage next time you launch? Unsure if this is a one-off due to bad IO exception handling.

**Comment by brentechols34** [comment]
I'll take some time today hopefully to profile everything and see if I can isolate what caused it. Thanks!

**Comment by brentechols34** [comment]
I can't reproduce anymore, and I haven't modified any of files involved. My guess is maybe I had something running that blocked network access? Some process interfering? I typically run without restart for 2+ weeks on average, and I have done a hard reset on my machine since then. My best guess is w/e was interfering was closed by the hard restart, and life is back to normal!
