### ISSUE TITLE
JodaTime dependecy is unnecessary

### ISSUE THREAD

**Issue by zhedar** [eivindveg/HotSUploader#35]
It is only used in `GitHubRelease` as a member variable, which is never set until now. It may be replaced by the Java8 Date and Time API classes (see [Jackson-JSR-310 datatypes]) or simple `java.util.Date`.  

Removing the dependency may also help reduce the memory footprint from Issue #3 a tiny bit.  

[Jackson-JSR-310 datatypes]: https://github.com/FasterXML/jackson-datatype-jsr310        "Jackson-JSR-310 datatypes"

**Comment by eivindveg** [comment]
It is implicitly imported by [Amazon S3](http://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-core/1.10.20), however. I wish I could simply use the Java8 datetime API, which I personally feel is much better.
