### ISSUE TITLE
[OSX] Please provide a tap for HotSUploader

### ISSUE THREAD

**Issue by thorstenschaefer** [eivindveg/HotSUploader#39]
It would be great if you could also provide a [brew] (brew.sh) tap, to install it using the homebrew system typically used on Macs.
Relevant information to create it are [the formula cookbook] (https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md) and [this tutorial] (http://formalfriday.club/2015/01/05/creating-your-own-homebrew-tap-and-formula.html).

**Comment by eivindveg** [comment]
I'll look into it. However, as this is a Java application, there is a pretty hard limit to what native support I can provide.

**Comment by thorstenschaefer** [comment]
As the new version just came out, I created a brew cask formula and submitted a pull request to the cask repository. You can find it here: https://github.com/caskroom/homebrew-cask/pull/14573
I'm not sure if you are using a build system, but if so it would be great if the cask update could be integrated into it. Thanks for providing the cool tool :)

**Comment by eivindveg** [comment]
This is a welcome blindside. However, the artifactId should match as I mentioned in the pull request. I'll look into integrating updates for this in the maven build system.

**Comment by thorstenschaefer** [comment]
I'm not sure which elements should match, can you clarify this? I looked into the hotslogs uploader POM and the artifact ID I find is: "hots-uploader-fx". You want to have the cask like it is, but with the 
first line 
"cask :v1 => 'hotslogs-uploaderfx' do"
changed into 
"cask :v1 => 'hotslogs-uploader-fx' do"
(and change the name of the cask similarly)? I'll check how I can update/reinitiate the pull request after you confirm.

**Comment by eivindveg** [comment]
I think it's actually better that we rethink the naming strategy of this app. FX is not a necessary part of the name. If we add more providers, calling it HotSLogs UploaderFX is also wrong. It could be simplified to something like just HotSUploader, with an artifact id and a tap name like hots-uploader. I'll create an issue for discussing this. Please hold off with the pull request until this is sorted. I assume changing names will affect updates.

**Comment by eivindveg** [comment]
We now have one pull request and two issues for this. However, I'm keeping this issue open until we have some sort of publish feature.

**Comment by eivindveg** [comment]
Just a heads up. Release 2.0 is looming, Once this is done, I'll notify the cask maintainers about the new artifact. IDs are as follows if you'd like to prepare your pull request:

GroupId: ninja.eivind
ArtifactId: hots-replay-uploader
Version: 2.0

**Comment by zhedar** [comment]
We also need to update the provided `url` to point to the 2.0 release then. It seems rather inconvenient that cask doesn't provide an automatic lookup for versions, but then again it's just a collection of binary links.
That's also something that needs updating in the future.

**Comment by eivindveg** [comment]
Release is out, @thorstenschaefer, and I've assigned the issue to @zhedar. Please collaborate with him to see this through or let us know if we should take over. Thank you for your patience.

**Comment by adityadalal924** [comment]
(I'm one of the maintainers of Homebrew Cask)

@zhedar The idea is that if you use `#{version}` in your url, the only thing that needs to be updated in the Cask over time is the version and shasum. We also do support an appcast stanza, so that in the future we can detect if an update is released, but that functionality isn't built yet.

I've commented in https://github.com/caskroom/homebrew-cask/issues/15562 with the chages that need to be made in order to finish up and merge the PR.

**Comment by zhedar** [comment]
@adityadalal924  Thanks for the feedback and the fast reponse.
So if `https://github.com/eivindveg/HotSUploader/releases/download/v2.0.0/HotS.Replay.Uploader-2.0.0.dmg` could be abstracted by `https://github.com/eivindveg/HotSUploader/releases/download/v#{version}/HotS.Replay.Uploader-#{version}.dmg`, that would be indeed much better.  
We considered to write a script that publishing releases to you a bit, do you have something to originate from already?

**Comment by adityadalal924** [comment]
Correct, that second URL does string interpolation correctly and will need minimal updating as time goes on (just version and shasum)

I personally use something like [cask-repair](https://github.com/vitorgalvao/tiny-scripts/blob/master/cask-repair) to automate the process to updating a Cask, but it seems like overkill in this situation. Of course, if you want to write something for auto-publishing updates as PRs, that would be awesome (and much appreciated for the community at large). Feel free to open up an issue at https://github.com/caskroom/homebrew-cask/ and we can discuss it further, including ideas for implementation, if you do decide to go down that route.

**Comment by adityadalal924** [comment]
Ended up making the changes, as they were a quick fix.

`brew cask install hots-replay-uploader` is now available (`brew update` if you don't see it).

**Comment by zhedar** [comment]
Thanks for you dedication, everything seems to work just fine. I'm actually impressed, that these changes are live so fast.
I will look into automation and create an issue with my ideas, when I organized them a bit.
