### ISSUE TITLE
15% of uploads fail with Status "FileNotFound"

### ISSUE THREAD

**Issue by KennethRMason** [eivindveg/HotSUploader#42]
I have ~100 files that have failed to upload.  Upon debugging, I see the error is due to a status of "FileNotFound".  Screenshot during debug below.  

A file that consistently reproduces this error is available here: 
https://drive.google.com/file/d/0B2BpClmT7DbNTDNmQ2JoNVNYc2c/view?usp=sharing

![debug](https://cloud.githubusercontent.com/assets/347322/10566543/ebc6543a-759e-11e5-9a5e-dba0af6ab22f.png)

**Comment by barrett777** [comment]
FileNotFound is a generic error.  Most likely these are an unsupported
replay, such as a Custom game with CPU player, or the store 'Try Me' mode.
Can you see what is shown for this replay in game?

**Comment by KennethRMason** [comment]
![e7afb381-09b2-4f30-96dd-48d6202268e3](https://cloud.githubusercontent.com/assets/347322/10566646/244e6eca-75a2-11e5-828f-ddf0092f3074.JPG)

**Comment by barrett777** [comment]
Yeah that is a Custom or VS AI game.  'Player X' are CPU names

**Comment by KennethRMason** [comment]
Shouldn't these show up as "unsupported" instead of as failed, in that case?

**Comment by barrett777** [comment]
Yeah :) Maybe next version

**Comment by KennethRMason** [comment]
Any information I can provide to assist?  I don't see any obvious fix in the code, other than observing "FileNotFound" and returning UNSUPPORTED, but that sounds like it could cause other errors to be misinterpreted.

**Comment by barrett777** [comment]
Nah this code is fine, it needs to be fixed directly in HOTSLogs.com / HOTS
Logs replay parsing project

**Comment by eivindveg** [comment]
I'm actually dropping support for the "unsupported game mode", and have added in a delete function. This is all ready, but there are various other things like a h2-database I'd like to get in before releasing.
