### ISSUE TITLE
Account combobox looks different then hero selection combobox

### ISSUE THREAD

**Issue by zhedar** [eivindveg/HotSUploader#44]
The account combobox looks slightly odd (when you click on it), compared to the properly working hero selection combobox. Maybe this shouldnt be a ComboBox, wouldn't a readonly textfield be a better match? 

**Edit**: Didn't consider you can have multiple accounts. Then the ComboBox makes sense. But shouldn't it look like the one from the hero selection then?

<img width="241" alt="bildschirmfoto 2015-10-21 um 12 24 34" src="https://cloud.githubusercontent.com/assets/6633403/10634053/4bc845a8-77ef-11e5-8d7a-d8ce652ffdc8.png">

**Comment by eivindveg** [comment]
It's a ChoiceBox, which despite the similarities are drastically different from ComboBoxes, which the Hero Select is one of.
I tries styling it up, but couldn't find out how to target it with css, and the source code for ChoiceBox made me no wiser. Will try again later.

**Comment by eivindveg** [comment]
Will try to use non-editable ComboBox instead of a choice box: this should be an automatic fix if it works as intended.

**Comment by eivindveg** [comment]
That fix, however, makes it gray out as it is not editable.

**Comment by zhedar** [comment]
I tried styling a ComboBox myself and it looks quite decent. The only thing that I recognized afterwards was that the arrow was still still blueish:

<img width="237" src="https://cloud.githubusercontent.com/assets/6633403/11012803/6d4c2cb8-84fa-11e5-8f81-d16dd23ff713.png">

Would using a `ComboBox` instead of a `ChoiceBox` work, or is the latter's functionality needed anywhere? I can't test this, because I only have a single account.

**Comment by eivindveg** [comment]
The problem is we'd have to set the combobox editable, or style an uneditable one to look like it's editable. Describe the blueishness? Could you open a pull request either way so we can review and discuss the code?

**Comment by zhedar** [comment]
The screenshot shows an read-only ComboBox styled like the hero details, so like an editable I guess. It's just the dropdown arrow that's light blue like in the screenshot, that should be changed to be white.

Yeah, i just replaced the ChoiceBox by a ComboBox and applied the style at it's listcell. I haven't worked with fxml yet, so there may be a better solution.

**Comment by eivindveg** [comment]
Based on what I see, the solution is excellent. I'll review the arrow bit once I've settled down from this heavy parser copy-pasta-reimplementation of a legacy project.(On a side note; I hope to god I'm not violating 100 licenes)

**Comment by zhedar** [comment]
Seems like the blue shade only occurs after the box was focused. It went away, after I selected the hero box. So it's just the selected field indicator. 

<img width="237" alt="bildschirmfoto 2015-11-07 um 03 15 29" src="https://cloud.githubusercontent.com/assets/6633403/11012996/d6986828-84fd-11e5-9067-b64c18c9b645.png">

I may prepare a PR then.
