### ISSUE TITLE
Application title is overly sophisticated

### ISSUE THREAD

**Issue by eivindveg** [eivindveg/HotSUploader#48]
When I first created this application, I pulled a "funky fresh" name out of the blue. This github repository is named HotSUploader, while the application is called HotSLogs UploaderFX. While this is currently a HotSLogs.com exclusive uploader, this may not also be so. The FX part of the name, while signifying that this is a JavaFX application, is not really necessary. I'd like more feedback on this, so we can move ahead with issue #39.

**Comment by thorstenschaefer** [comment]
My 2 cents: The name "HotSLogs Uploader" sounds good to me - describes exactly what it does and doesn't have the technology used (FX) in it's name. If you possibly want to include other sites to upload to, "HotS Uploader" or "HotS Replay Uploader" would be the first names that pop into my mind.

**Comment by zhedar** [comment]
I agree with @thorstenschaefer, "HotS Uploader" or "HotS Replay Uploader" would be well suited names. Personally I like the first more, since it's shorter.  
Another possibility would be to add "Universal" in front to capitalize, that it runs on all platforms and supports multiple upload providers.

**Comment by eivindveg** [comment]
Adding universal does make it longer again though, but would result in a much more precise artifactId(hots-uploader-universal)

**Comment by thorstenschaefer** [comment]
No strong opinion on the naming part, but I want to highlight that names like 'universal' are not as precise as it seems to be. For instance, it might be clear for the developers that universal means cross-platform, but other persons might think it can upload QM/HL/TL games (which would be true for the tool) or have a completely different kind of concept in mind.

**Comment by eivindveg** [comment]
A few more of my thoughts I'd like feedback on:

This is an unofficial uploader, but @barrett777 has had no problem associating logos and names with his service so far. The current HotSLogs part of the name does kind of let on where the replays are uploaded. If we go for HotSUploader with no mention of HotSLogs in logo or name, this could become less given. If multi-provider is added(which, I unfortunately do not see the point in due to HotSLogs being so dominant that other providers give no reason for you to upload, but that's not a bridge I'd like to burn yet), we would have to clearly distinguish what the app is doing. My current idea is replacing the current retry-icon with a logo representing each service.

Short and sweet should do it, but HotS Uploader is not as clear as HotS Replay Uploader. This isn't so much a problem with HotSLogs Uploader because it's pretty obvious what you upload to it.

**Comment by zhedar** [comment]
So what about StormReplay Uploader? That should make it clear, since the file extensions are named this way and a quick google search leads to HotS ressources afterall. This would be as long as  HoTs Replay Uploader, but it surely *feels* shorter...

**Comment by eivindveg** [comment]
StormReplay Uploader sounds both concise and cool enough to pass as an app. Think we've narrowed down the options to HotS Uploader, HotS Replay Uploader and StormReplay Uploader? Any final thoughts on these three?

**Comment by allanjackson** [comment]
You could put a strawpoll up on reddit if you want to get a better feel for people's opinions. I personally like having "HotS" in the title.

**Comment by eivindveg** [comment]
Threw in a few more strawpolls on things I'm not sure about!

https://www.reddit.com/r/heroesofthestorm/comments/3pz2d8/hotslogs_alternative_uploader_polls/

**Comment by eivindveg** [comment]
There's a marginal lead for HotS Replay Uploader as per right now on http://strawpoll.me/5814660/r

This will result in an artifactId of hots-replay-uploader for version 2.0. I'm also changing the groupId to match my domain(eivind.ninja), so the complete Maven reference for version 2.0 will be:

GroupId: ninja.eivind
ArtifactId: hots-replay-uploader
Version: 2.0

This will be branched out to develop right now, though no ETA on the release.
