### ISSUE TITLE
OSX - Application Home fails with unconventional user.home

### ISSUE THREAD

**Issue by eivindveg** [eivindveg/HotSUploader#5]
Mac user wolf reports having moved his Home directory to another drive, and the $HOME/.hots-uploader/ directory becomes invalid as a result. A fix to conform to OSX library directories was rolled out in a7a2953 which is part of v1.0-rc.1 but has so far not received feedback.

**Comment by greatman** [comment]
You can do ~/Library to redirect to the current user home. the ~ equals the user home directory in Linux/OSX.

**Comment by eivindveg** [comment]
I prefer using the System.getProperty("user.home") method, since then I can override that property in unit tests to build some temporary directories within the project. User provided output shows that the user.home property does point to ~, so that shouldn't be the issue.

**Comment by wolfposd** [comment]
current masterbranch works

**Comment by eivindveg** [comment]
Current master branch works, but the RC2 download does not?

**Comment by wolfposd** [comment]
rechecked, works  ¯\_(ツ)_/¯ 

time to install linux I guess....
