### ISSUE TITLE
@Zhedar: Contact Request

### ISSUE THREAD

**Issue by eivindveg** [eivindveg/HotSUploader#58]
@zhedar 

I have received open source licensing for the [YourKit Java Profiler](https://www.yourkit.com/features/) for this project. Could you please send me an e-mail(details found in pom.xml) indicated whether you're interested in a license? If you are, please also include your full name(first and last), and I will isse you your license once I receive it.

**Comment by eivindveg** [comment]
*poke*, @zhedar

**Comment by zhedar** [comment]
I already sent you a mail yesterday. Will resent it with googlemail now, maybe your spam filter ate it up?
