### ISSUE TITLE
Replay files will be flagged as new, although already updated

### ISSUE THREAD

**Issue by zhedar** [eivindveg/HotSUploader#59]
I've got this problem with the snapshot since we started branching out for 2.0. At first I thought, it was caused by the new FileStore, but we are still using the JsonFileStore, aren't we?

I'm not sure if this error is on our or on hotslogs side, I just see, that the replay gets parsed, will be flagged as new and then fails, because it is already uploaded there (`filenotfound` status response). But it looks like it's the client, because the replays seem to be duplicated (count as uploaded and new).

Left: current release(1.3.1), right current 2.0-SNAPSHOT from develop.
<img width="868" src="https://cloud.githubusercontent.com/assets/6633403/11137367/35e1c636-89b7-11e5-9f91-3ee895ff14df.png">

I may dig deeper into this later on and provide some replay files if needed.

**Comment by eivindveg** [comment]
Saw something similar last night. I think it has something to do with #61. If you restart the app, it handles them.

**Comment by eivindveg** [comment]
@barrett777, which String do you return if you can't find the S3 file referenced?

**Comment by zhedar** [comment]
How should it handle them? I can exactly reproduce this state every time I start the app, so it's a persisting problem. I also removed all the JSON files to completely retry it. The same replays will remain.

At the retry I also encountered another bug, the list of new replays won't get updated, since `files.remove(replayFile);` fails with a `ArrayIndexOutOfBoundsException: -404` for every upload. 
That one will be fixed by an application restart, as the property files will be created properly in this case.

Here's a sample stacktrace:

    at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.remove(ModifiableObservableListBase.java:183)
	at javafx.collections.ModifiableObservableListBase.remove(ModifiableObservableListBase.java:171)
	at ninja.eivind.hotsreplayuploader.services.UploaderService.lambda$4(UploaderService.java:137)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.concurrent.EventHelper.fireEvent(EventHelper.java:219)
	at javafx.concurrent.Task.fireEvent(Task.java:1356)
	at javafx.concurrent.Task.setState(Task.java:723)
	at javafx.concurrent.Task$TaskCallable.lambda$call$501(Task.java:1434)
	at com.sun.javafx.application.PlatformImpl.lambda$null$174(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

**Comment by zhedar** [comment]
I just tested the webservice and found out, that it can both return `success` and `duplicate`, I added the check for the first aswell, so now all replays will get flagged correctly. We could also check for the status `FileNotFound` though. 
@barrett777, is this intentional? 
Example: 

    https://www.hotslogs.com/UploadFile?Source=HotSLogsUploaderFX&ReplayHash=647cc2c5-3d6d-755a-3ac1-7845fec4c300
  return `success`. Replay is from a valid QM game, already uploaded.


The problem with that is, that now all replays have vanished from the list. Even the versus ai games seem to be 'uploaded'.

By the way was the file count bugged in the version before? I discovered, that the total count in the new version seems to be right, if compared to the number of files in the directory.

**Comment by barrett777** [comment]
What happens if you upload that replay to HOTSLogs.com?

**Comment by zhedar** [comment]
Uploading via the site just yields `Maintenance: 2`. Are you currently in maintenance mode?

**Comment by eivindveg** [comment]
This should be backed with a fully mocked unit test that reflects the Provider's actual response for this replay file. Test should verify the replay is tagged properly as either EXCEPTION or UPLOADED.

**Comment by barrett777** [comment]
I'm not currently in Maintenance.  HOTS Logs will also return 'Maintenance' if something unexpected happens while parsing.  Usually this happens with a VS AI game or some other strange replay, such as the 'Try Me' mode in the in game shop.  Are you sure that happened with a Quick Match game?

And when you are providing the replay hash to HOTS Logs, I just check to see if I have a replay saved in my database with that hash.  I don't save any of the VS AI matches so they will always show as 'Success' when you check the replay hash.

**Comment by zhedar** [comment]
Thanks for the insight.
Meeh, my bad. I just rechecked and I played 2 games of BoE that day. I just dropped the wrong file in there. So everything seems to be fine on your side. Just the `success` was a bit misleading.

**Comment by eivindveg** [comment]
I'm not sure what causes this; it's a change commit that cascades from the observable list we use as base down to the sorted list we display. The index returned is negative, which shouldn't be possible  considering the implementation used to determine it is binary search.

... we have a race condition.

**Comment by eivindveg** [comment]
Oh. Two different issues. I read the stack trace when I started reviewing.

On the first, I think we need need to tag FileNotFound as EXCEPTION.

For the array index out of bounds:
The JavaFX environment is highly concurrent to the point that sorting the list using the SortedList implementation just doesn't seem to catch up. I'm not sure exactly why the BinarySearch implementation in java.util.Arrays ends up returning a negative index; it's possible the index moved due to a sort while another item was being removed, during the removal process. In that case, we're just too fast.

I think this issue is manifest by sorting the list, and the blazing speed of the parser.

**Comment by zhedar** [comment]
I should open have opened a new issue on the sorting thing, so we can track their status' separately. But in the end they both end up cluttering the new replay files list.

1. `FileNotFound` seems to be returned, if something is wrong with the hash, e.g. if it has the wrong length. So tagging it as `EXCEPTION` may be ok.

2. I reviewed all points, where items get added or removed from the list. They all happen on the `Application` thread and therefore shouldn't summon concurrency issues. The thing is, that sorting a list (with so few items in it) should be always faster than I/O-actions. (Although I'm testing on a SSD and that's why the bug triggered sometimes.)

**Comment by eivindveg** [comment]
Does the sorting happen on the application thread though?

**Comment by zhedar** [comment]
A quick `Thread.currentThread().getName()` check in the Comparator yielded, that sorting indeed doesn't happen on the application thread, for some reason it happens on the `AppKit` thread on my machine, which is something like an apple cocoa event thread, which I've never heard of. Has windows something different?

**Comment by zhedar** [comment]
It seemed to be the `SortedList` wrapper indeed. I worked around this by replacing it with manual sortings. That's not the best solution, but atleast I cannot reproduce the problem anymore. Before that it occured almost every time I retried an upload and it succeeded.

**Comment by eivindveg** [comment]
Ref JDK bug: the solution seems to map the returned integers to {-1,1} and only returning 0 for o1.equals(02). The fallback should be a traceable exception?

**Comment by eivindveg** [comment]
In this case, the equals should even be ==

**Comment by zhedar** [comment]
If you're not able to fix it with this solution, [here's my workaround](https://github.com/zhedar/HotSUploader/commit/32b50a18dbcea7c6de0c35eeaf53cf3d5b187c1e). It's not the favourable though, because one could easily forget the sorting when adding some other interactions.

**Comment by eivindveg** [comment]
I agree. However, it may be the strongest fail safe we have for that threading issue. Will try hard-specifying the comparator to "contract or exception". In that case we will at least get a very clear indicator as to what goes wrong.

**Comment by eivindveg** [comment]
Reviewing the current comparator, it seems it can return 0 without ever checking the name at all. This should be added the front of the comparison; more specifically we should adopt the assumption that one of the two inputs during a remove operation is the file being removed and that the other is a candidate for same identity. This should be prepended to the current compare in addition to claiming that no other replay is equal.

**Comment by eivindveg** [comment]
Also, cannot reproduce the original issue. Is that still around?

**Comment by zhedar** [comment]
The original issue was, that AI games that were previously ignored (before the design rework) popped back up as new games (which had exceptions then). This was kinda fixed by #61, but now the non-uploaded vs AI games count as uploaded though. So the upload count is higher than the real number of uploaded files.

**Comment by eivindveg** [comment]
Will look into just not showing bot games. Will need to refactor it a bit though.
