### ISSUE TITLE
Source code not documented

### ISSUE THREAD

**Issue by eivindveg** [eivindveg/HotSUploader#6]
See title. A proper release for an open source product should be documented to allow other developers to participate.

**Comment by zhedar** [comment]
Is this still a thing? Most of the application is still undocumented. I [began to add class level javadoc](https://github.com/zhedar/HotSUploader/commit/2dfe8ba3c221012191803ed30099e8a15f363f89) to some of the classes, but this also needs a bit of reverse-engineering and takes some time, so it's not that much yet.

Also would you be ok with removing of author tags? [Who needs them](http://www.theinquirer.net/inquirer/news/1037207/apache-enforces-the-removal-of-author-tags), if there's version control.

**Comment by eivindveg** [comment]
Class level Javadoc should be a minimum, yes.

Actually, the application is "licensed" under the Apache 2.0 license. Every source file should have the contents of https://github.com/eivindveg/HotSUploader/blob/develop/LICENSE inserted above the package declaration.
