### ISSUE TITLE
Retry upload button feels inresponsive

### ISSUE THREAD

**Issue by zhedar** [eivindveg/HotSUploader#60]
Since the material design UI rework, the retry button feels unresponsive, because there is no visual feedback, if the button was pressed immediately.

After some trying around while writing this issue I found out, that you need to double click the retry icon. Shouldn't that behave like a button and work an a click, not a double click?

Sometimes it feels like it works on a single click though, that's what me left confused. Maybe, if the row was selected and the button gets clicked shortly thereafter.

**Another thing, related to the responsiveness:**
Now that we have replay parsing, maybe we should add another status besides idle and uploading? Or would file handling and parsing be that quick, we wouldn't see the status change at all?

**Comment by eivindveg** [comment]
I think this might have to do with layers. I remember testing this and it working, but that was before I added the delete button.

About the application status: if we make the preparsing bit in HotSLogsProvider part of the Provider class, we could pull the parsing check logic up to UploadTask. That integrates a lot better with UploadService, which could be given access to the StatusBinder.

**Comment by zhedar** [comment]
I found the cause for the 'inresponsiveness'. The onclickListener is registered on the refresh icon, but it's only triggered, if you click directly at the white part of the icon. If you click in the transparent middle or between the arrows, it won't get triggered. That's when the row's listener kicks in, which also tries to reupload the file on a double click. That's probably where my confusion came from.

**Comment by zhedar** [comment]
Found a rework for this by replacing the `ImageView` with a tweaked version of your `ImageButton`. This will fix the collision detection with the icon (handler will trigger even if clicked in the middle of the icon) and will also provide a visual feedback, if the button was clicked. Is this compliant with the material design? Otherwise I could remove it again.
