### ISSUE TITLE
Don't upload files with unsupported game mode

### ISSUE THREAD

**Issue by zhedar** [eivindveg/HotSUploader#61]
Now that we've got a basic parsing functionality, we may also check for the game having the right game mode (e.g. not vs ai), before uploading at all.

At the moment the client will always update a new game with unsupported gamemode, because hotslogs will flag them as new, which isn't wrong. But this could possibly be prevented.

We would need to add the gamemode extraction in the ReplayParser though, as it isn't already there (as far as I've seen yet).

With this information, It *could be* possible to hide incompatible games from the new replays, so only real new or failed replays would show in the list. I'm just not sure, if this was possible before aswell and was just removed with the redesign.
Any opinions on these ideas?

**Comment by barrett777** [comment]
If you want to, it's easy enough.

AI players have the name 'Player 1', 'Player 2' etc.  Real players can't
have spaces in their name.  You could just check if any player names have
spaces in them and not upload those

**Comment by zhedar** [comment]
That sounds doable, so I guess it would work for Training aswell?

**Comment by barrett777** [comment]
Yup same thing

**Comment by eivindveg** [comment]
So the real question should be whether StormParser should take care of setting the information or if it should be inferred from the player names in the uploader. Where do you set this in your parser, @barrett777?

**Comment by zhedar** [comment]
But since you dropped support for the unsupported game modes a while ago, how could we handle that? Showing these replays under the new section is quite misleading and if you've got a lot of those files it can get a bit confusing.

**Comment by barrett777** [comment]
I check for AI players in the replay.attribute.events file, but using player names should be fine anyway

My spot: https://github.com/barrett777/Heroes.ReplayParser/blob/master/Heroes.ReplayParser/replay.attributes.events/ReplayAttributeEvents.cs

**Comment by eivindveg** [comment]
Will flag this in the parser once I get done with my current two home exams that are due Sunday.(Embedded Systems and Programming in C for Linux yay!)
