### ISSUE TITLE
Test coverage is horrible

### ISSUE THREAD

**Issue by eivindveg** [eivindveg/HotSUploader#8]
It would be irresponsible to do a final release for a product that doesn't have proper test coverage

**Comment by ehatle** [comment]
I have created some JUnit 4 tests that seem to be running fine. I can keep coming up with some more in the future.

I would like to gain a contributor status so that I can upload these changes continuously

**Comment by eivindveg** [comment]
Contributor status is only handed out for direct uploads to new releases while they're being drafted. I really do appreciate pull requests though!
