### ISSUE TITLE
CMD + Q & menu > quit uploader not working

### ISSUE THREAD

**Issue by MiguelDebruyne** [eivindveg/HotSUploader#81]
When I CMD + Q or try to quit the application through the top menu it minimises the application window to the dock. The only way to quit the application is through right clicking on the icon in the dock and quitting it there. After I have done this the application does not open anymore. It starts up and quits before opening any windows.

Here are my specs:
OS X Yosemite 10.10.5
MacBook Pro (15-inch, Late 2011)
2,4 GHz Intel Core i7
16 GB 1333 MHz DDR3

**Comment by zhedar** [comment]
I couldn't test this on Yosemite, only on El Capitan (10.11), normally CMD + Q should quite the application in any case. Can you exit the application via the tray icon menu in the system bar?

Can you let the app upload all of your files and then try again so close / minimize it?

Also you could try to start the jar from the Terminal via `java -jar HotS.Replay.Uploader-2.0.0.jar`.

Thanks for your feedback.

**Comment by eivindveg** [comment]
Please check this behavior, @FredrickB

**Comment by zhedar** [comment]
@MiguelDebruyne, any news on this? Have you tried removing the folder? I would like to make sure, this is issue is related to our db changes and not OS X in general.

**Comment by zhedar** [comment]
@MiguelDebruyne We just pushed a bugfix release, please check if the issues still persist.

**Comment by davextreme** [comment]
Same issue here. You can right-click in the Dock to kill it, but quitting from the menu or using Cmd-Q doesn't work. Minimizing instead of quitting is shady Windows-like behavior! :)

**Comment by zhedar** [comment]
Are you sure, CMD + Q won't work? That should work in any circumstance, although the quit via menu option indeed only minimizes the application, I haven't found a workaround for that yet.
Also, what version of OS X are you on, @davextreme?

**Comment by davextreme** [comment]
@zhedar Ah, yes. If you use CMD + Q it minimizes and then quits.

**Comment by eivindveg** [comment]
Thanks for verifying, @davextreme. Otherwise, this issue is stale and not currently reproducible. Closing.
