### ISSUE TITLE
2.0 does not start at OSX 10.11

### ISSUE THREAD

**Issue by sbusemann** [eivindveg/HotSUploader#82]
I'm using OSX 10.11 and the HotSUploader does not start. Konsole says: "com.apple.xpc.launchd[1]: (HotS Replay Uploader.266272[3850]) Service exited with abnormal code: 1"

**Comment by zhedar** [comment]
Can you try what I suggested in #81? That is primarily removing the `~/Library/Application\ Support/HotSReplayUploader/` folder, but then also trying to start the jar, so we can analyze what went wrong from the logs.

**Comment by sbusemann** [comment]
Removing the ~/Library/Application\ Support/HotSReplayUploader/ folder solves the problem. The application starts now.
