### ISSUE TITLE
Closing the window doesn't send the program to the tray

### ISSUE THREAD

**Issue by ltrain23** [eivindveg/HotSUploader#84]
In the old version, clicking the X in Windows would remove the app from the taskbar and send it to the tray. Now, it closes the app completely. Would like to have this feature back.

EDIT: Nevermind. It's there. But the logo is white, so I can't see it. Combine this with my other issue, please.

**Comment by zhedar** [comment]
Closed in favor of #83.

**Comment by eivindveg** [comment]
Solution similar to #52 needs to be added for Windows. Solution should attempt to read the task bar colour of the currently active theme and select the icon closest to inverse of that colour.

**Comment by eivindveg** [comment]
... once again closing in favour of #83
